# Debe ser único en tu instalación de SonarQube
sonar.projectKey=spring-boot-app
sonar.projectName=Spring Boot Application

# Rutas relativas al archivo sonar-project.properties
sonar.sources=src/main
sonar.tests=src/test
sonar.java.binaries=target/classes
sonar.java.libraries=target/**/*.jar

# Lenguaje
sonar.language=java
sonar.sourceEncoding=UTF-8

# Configuración de pruebas
sonar.junit.reportsPath=target/surefire-reports
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Excluir archivos
sonar.exclusions=**/*.sql, **/*.properties, **/*.yml, **/*.yaml
sonar.test.exclusions=**/test/**/*

# Java 21
sonar.java.source=21
sonar.java.target=21